// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/lib/supabase-types-fix';

const SUPABASE_URL = "https://frkfrvbwhnvtvywgmvzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZya2ZydmJ3aG52dHZ5d2dtdnp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTE5NTAsImV4cCI6MjA2ODA2Nzk1MH0.vR2M3Iqws4-g8zPYkZtFCaUX7umYtaxemacc1IwADS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});